// GENERATED by train_export.py - do not edit by hand.
// Decision tree trained on 24,000 links. Accuracy 82.2%
function phishingRisk(f) {
  if (f.length <= 17.5) {
    if (f.length <= 13.5) {
      if (f.words <= 2.5) {
        if (f.bad_ending <= 0.5) {
          if (f.ip <= 0.5) {
            return 0.13;
          } else {
            return 1.0;
          }
        } else {
          if (f.dots <= 1.5) {
            return 0.94;
          } else {
            return 0.0;
          }
        }
      } else {
        if (f.length <= 12.5) {
          if (f.length <= 7.5) {
            return 0.0;
          } else {
            return 0.97;
          }
        } else {
          if (f.no_https <= 0.5) {
            return 0.17;
          } else {
            return 1.0;
          }
        }
      }
    } else {
      if (f.at <= 0.5) {
        if (f.dash <= 0.5) {
          if (f.bad_ending <= 0.5) {
            return 0.27;
          } else {
            return 0.98;
          }
        } else {
          if (f.no_https <= 0.5) {
            return 0.41;
          } else {
            return 0.83;
          }
        }
      } else {
        if (f.dots <= 1.5) {
          return 1.0;
        } else {
          if (f.length <= 15.5) {
            return 0.67;
          } else {
            return 1.0;
          }
        }
      }
    }
  } else {
    if (f.length <= 21.5) {
      if (f.no_https <= 0.5) {
        if (f.dots <= 1.5) {
          if (f.length <= 20.5) {
            return 0.58;
          } else {
            return 0.75;
          }
        } else {
          if (f.at <= 0.5) {
            return 0.31;
          } else {
            return 1.0;
          }
        }
      } else {
        if (f.dots <= 2.5) {
          if (f.dash <= 0.5) {
            return 0.71;
          } else {
            return 0.92;
          }
        } else {
          if (f.at <= 0.5) {
            return 0.38;
          } else {
            return 1.0;
          }
        }
      }
    } else {
      if (f.length <= 25.5) {
        if (f.no_https <= 0.5) {
          if (f.at <= 0.5) {
            return 0.75;
          } else {
            return 1.0;
          }
        } else {
          if (f.dots <= 1.5) {
            return 0.98;
          } else {
            return 0.87;
          }
        }
      } else {
        if (f.length <= 28.5) {
          if (f.dash <= 0.5) {
            return 0.91;
          } else {
            return 0.99;
          }
        } else {
          if (f.length <= 30.5) {
            return 0.97;
          } else {
            return 1.0;
          }
        }
      }
    }
  }
}
